on:
  push:
    paths:
      - '**'
      - '!**.md'
  pull_request:
    paths:
      - '**'
      - '!**.md'
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch --all --tags --force
          shards install
          LOG_LEVEL=debug crystal spec
